### ISSUE TITLE
Final TODO List for TKL Consideration TKL-Final-RC1

### ISSUE THREAD

**Issue by DocCyblade** [l-arnold/tkl-nomadic-odoo#26]
Use this post to keep track of a final TODO list, this TODO list could create one or more issues. Any issues that would be created, just post a link to this issue so it's cross linked. Also tag it with the tkl-final-rc1 tag.
- [x] Update confconsole.txt (remove Samba references)(remove webconsole ref)
- [x] Documentation Approach  (separate issue for this (will be focused on DOCS folder)).
- [ ] Load Backup of openerp-server.conf in etc/odoo  as openerp-server-backup for safety
- [ ] Review openerp-server-man.conf (for relavence or usefulness)
- [ ] If Connector Left in, update etc/init.d/openerp-server to reflect outlined changes for jobrunner in connector (see citation below - landis has changes built in beta 02 working SERVER)
- [ ] Optional but desired  Check that ADDONS added actually load and do something  (I - LA - have a checklist to go through..  A few hours looking at OCA)
- [ ] Check that Logs being Generated and Turned Over for (x time period)
- [ ] Put link for odoo "database managment" into Web Console as it is in ConfConsole
- [x] (SHOULD NOT MAKE DEFAULT ~~Got whtmltox (or whtmltopdf) functioning.  Check with any "generated document" ie quotation~~
- [x] (SHOULD NOT MAKE DEFAULT~~Workers = 2  (not 0) unless breaking whtmltox  (connector wants min 1)~~
- [x](SHOULD NOT MAKE DEFAULT) ~~Debug Memory Limit Hard Minimum (add to openerp-server.conf)  when jobrunners are used.~~
  Was able to get past this:   Documented here:https://github.com/OCA/connector-magento/issues/152
  - [x](SHOULD NOT MAKE DEFAULT) ~~Workers = 2  (not 0) unless breaking whtmltox  (connector wants min 1)~~
- [x] ~~Debug Memory Limit Hard Minimum (add to openerp-server.conf)  if jobrunners are used.~~
- [ ] Check process security
- [ ] Check config file security.
- [ ] Final code cleanup / check 
- [ ] Final build tests CHROOT
- [ ] Final build test ISO
- [ ] Final build test Full ISO install
- [x] ~~Check "reboot" cycles.  From ConfConsole getting 50%.  Half say "reached target shutdown" but do not shutdown...  Either that or I am impatient. (LA)  (subsequent 3:  2 did not reboot.  3rd did)~~  works well enough.  Seems not an Odoo issue.
- [ ] Other Finals....

Landis Can Edit.  Can also see how to make a check Box  (Can Check without being in EDIT MODE!)
- [x] test check.... (put an X not a space in there)

**Comment by DocCyblade** [comment]
@l-arnold I think you should be able to edit the post, I created the check boxes so you can break down a issue in to parts. on the list view of issues it shows how many todo marks are left with a progress bar. Pretty neat!

We can add to this list, would like to have @JedMeister chime in to add to this list so we don't forget anything. After beta 2 is tagged, this is where we can have @JedMeister recommend or let us know of things that need to be changed or improved for consideration.

**Comment by l-arnold** [comment]
@DocCyblade Sounds good.  I will see if I can edit the list.  Can we "check the list"  I know that
"(~~)"before and after"(~~) will cross things out.
Parenthesis left, tilde, tilde Parenthesis Right  text to cross out  Parenthesis left, tilde, tilde Parenthesis Right

**Comment by l-arnold** [comment]
Quick Summary on my side.
It looks like we can get PostFix working by just including Some Documentation, otherwise we would need an Inithook to define the "catchall - email address" and set it into POSTFIX.  This is pretty easy and documented as to what should be set in the Postfix issue.

TKLBAM is effectively backing up and restoring via Shell.  The TKL Cert gets a little messy after wards.  Certified CERt Works fine.  All Data and Files move through very fast and without errors.  Again NOTE the TKL Cert is messy afterwards though.

WebConsole:  I still like it very much but have taken the a2ensite call for it out of the current Pull Request.  I have not heard anything otherwise so I will process the Pull so that I can also remove Samba.

This will leave the GIT Process Subject.  We really need this resolved to "assuredly" know that our DATA MIGATION issue is solved, but on my tests yesterday it was working as designed using the Process Bounce that pulled openerp.init start -u (database) -d (database) in the "UP BOUNCE" rather than the Service Call that stopped the service.

One Strong Rational for keeping the WEB CONSOLE in Place is that it provides an opportunity for better access to Documentation.

I realize also, that perhaps the best "Documentation" foundation would be a WIKI on the Web rather than something internal.   A simple Link to that WIKI might be sufficient.

All that I can see on my side right now.  I think this is closing in.

**Comment by l-arnold** [comment]
I am moving my general commentary to "communications" issue".  Lets have this focus on the punch list.

**Comment by l-arnold** [comment]
BETA 2 Efforts (2 parts here)

dev-wip1  Branch loads well after merges 9-12-15
Builds Database
admin password can be changed and recorded

----------
(DEV BRANCH MAJOR PROBLEMS)

RECOMEND WE Move DEFAULT to DEV-WIP1 and possibly "delete" or rebuild DEV

Synopsis:
First DEV folder on TKLDEV causing problems.  Cannot even Delete.  Files in "build" fighting 
"rm -rf build"
(Also was subject to Git Desktop work on Landis' but everything is showing good.  Don't understand)

I new Folder build on TKLDEV, after new clone and makes results in sort of error experienced earlier today

-------
this branch may not deserve the focus.  Comments ?  Outside tests?
-----:

fab-chroot build/root.patched --script /turnkey/fab/common/conf/adminer-apache
Enabling site adminer.
To activate the new configuration, you need to run:
  service apache2 reload
fab-chroot build/root.patched --script /turnkey/fab/common/conf/adminer-pgsql
fab-chroot build/root.patched --script /turnkey/fab/common/conf/php
sed -i /^memory_limit *=/ s/= *[^ ]\+/= 32M/g /etc/php5/apache2/php.ini
sed -i /^post_max_size *=/ s/= *[^ ]\+/= 16M/g /etc/php5/apache2/php.ini
sed -i /^upload_max_filesize *=/ s/= *[^ ]\+/= 8M/g /etc/php5/apache2/php.ini
sed -i /^memory_limit *=/ s/= *[^ ]\+/= 32M/g /etc/php5/cli/php.ini
sed -i /^post_max_size *=/ s/= *[^ ]\+/= 16M/g /etc/php5/cli/php.ini
sed -i /^upload_max_filesize *=/ s/= *[^ ]\+/= 8M/g /etc/php5/cli/php.ini
sed -i /^xcache.size *=/ s/= *[^ ]\+/= 32M/g /etc/php5/mods-available/xcache.ini
fab-chroot build/root.patched --script /turnkey/fab/common/conf/pgsql
+ set postgres
+ ls /etc/postgresql/
+ PGSQL_VER=
+ CONF_DIR=/etc/postgresql//main
+ pg_dropcluster --stop main
Usage: /usr/bin/pg_dropcluster [--stop] <version> <cluster>
/usr/share/fab/product.mk:476: recipe for target 'build/stamps/root.patched' failed
make: *** [build/stamps/root.patched] Error 1
root@tkldev products/tkl-odoo-dev# ^C
root@tkldev products/tkl-odoo-dev#

**Comment by DocCyblade** [comment]
Looks like the build failed and services are still running. That's why it won't build. 

Try rebooting your tkldev box.

**Comment by l-arnold** [comment]
Thanks ken.  Deleted finally.
One more try on Dev build also.

**Comment by l-arnold** [comment]
Was posting this a few days ago.  Seems to not have posted:

## Probably apparent by now

New "branch" created "RC"  based on dev-wip1.  This shoold be able to replace purpose of "Dev" branch and should be fed to "master" quite soon.  No specific projects other than some security testing seen (at least by me) to be done.

Perhaps some sundry "documentation" files can be moved from "dev" branch but dev-wip1 workin for me.  Not in a position to build a new TKLDEV box to get Dev running right now.  Could do so next week but it sounds like Dev otherwise is building for folks (just not me).

**Comment by JedMeister** [comment]
Have you tried rebooting your TKLDev box? Usually that solves issues like this...

**Comment by l-arnold** [comment]
Tried a few times.

I will look at Ken's merges.  Prob will solve.  
Not a huge deal to make a new Build if needed.  Your fuser -k command in the other thread might be all that is needed also.

fuser -k build/root.patched

**Comment by l-arnold** [comment]
On a new TKLDEV, b - dev indeed built.  Tried one more time today on the old even after the fuser command above but still same failure.

Very strange that every other branch would build but not that one.  I guess now I need to see if it "builds in the flesh."  Will try a VM.

**Comment by JedMeister** [comment]
It is really weird... Although sometimes what you've done (started again) is quicker and easier rather than troubleshoot what is actually wrong...

**Comment by l-arnold** [comment]
Agreed.  I just wanted to be sure something was not actually wrong with Dev (which both of you had already confirmed, but anyway).

I've been bombing Odoo with real use today.  Pretty amazing system.  I do need to find the module that allows me to have multiple images for a product just now.  Will add that to the "list".  We can work on how to handle options of the sort.  Would be really nice if we could have it all be "post install" webmin additions but time is a ticking.

**Comment by l-arnold** [comment]
![service unavailable](https://cloud.githubusercontent.com/assets/5673448/10038532/9dd7ea1e-6184-11e5-9f32-2399fa439942.jpg)
DEV (beta 2) report.
Built:  Ran Updates:
Did not Start on firstboot into Odoo
Did not "Restart" from ConsConsole command (seemed to hang).

Apache was started on Reboot, but Odoo Service Unavailable still>

[service unavailable](https://cloud.githubusercontent.com/assets/5673448/10038524/7d34bbc0-6184-11e5-95e8-1564cebeb9a3.jpg)

Will try again new with same ISO.

DEV-WIP1 is Working.  Not clear on the differences between the builds at this juncture.

**Comment by JedMeister** [comment]
Did you do any troubleshooting? My guess is that there is something not quite right with the Odoo service and that it's not starting... You can check on it with:

```
service openerp-server status
```

It's actuall a python app so another route (to see if there is an odoo process running even if the server command reports it's not) would be this:

```
ps aux | grep python
```

You will get one result from the grep command; but if you get any others then python is running something...

Also it may be worth seeing if there is anything in the logs. IIRC we configured to log to be in /var/log

**Comment by l-arnold** [comment]
No troubleshooting as yet.  Was going to try again first as I had some long delays on install.  Seemed that the "update" post process did not run at the end.  That said, it should have run at Reboot... at least it did in the past.

Will test in the AM.  Just hit midnight and you are still working sir.  You are always working it seems.  Do you sleep? :smile:

**Comment by JedMeister** [comment]
It's 4 in the afternoon here so yep I'm working! :smile: I do often work weird hours although I do sleep! :smile:

**Comment by l-arnold** [comment]
I thought that was the calculation for you.  Just sometimes it must be 2 AM.  Back at it, just barely this AM here.

**Comment by l-arnold** [comment]
UPDATED
Ran again the Current DEV New Build.  More info this time:
I did not load Updates at Install Time this time
It appears that the "restart services" is doing just a short run.  (one maybe 2 entries showed up on the console briefly)

Reboot Cycled this time.
Odoo System not running.

Running the Inithook 97 Yo Yo
(OpenERP Service not Locatable).  perhaps something with the name as I think we may have changed something there last week.  Here is the Shell log)

root@tkl-odoo-dev ~# systemctl stop apache2.service
root@tkl-odoo-dev ~# systemctl stop openerp-server.service  
Failed to stop openerp-server.service: Unit openerp-server.service not loaded.  
root@tkl-odoo-dev ~# systemctl stop postgresql.service  
root@tkl-odoo-dev ~# systemctl start postgresql.service  
root@tkl-odoo-dev ~# systemctl start openerp-server.service  
Failed to start openerp-server.service: Unit openerp-server.service failed to load: No such file or directory.  
root@tkl-odoo-dev ~# systemctl start apache2.service

**Comment by l-arnold** [comment]
What the settings in Running Beta 1 look like from Webmin:
python /opt/openerp/odoo/openerp-server --config=/opt/openerp/odoo/openerp-serve ...

**Comment by l-arnold** [comment]
Working on a "cloud restore" to Lapp for Testing.  Get the following.  Another reason to get this into the program.  Broken record I know.  Worth the test anyway.  (you can't --force-profile=lapp on restore)

Restoring a ODOO backup to a POSTGRESQL appliance may create complications.
For best results try restoring instead to a fresh ODOO installation.

(Use --force to suppress this check)

Do you want to continue? [yes/no] y

**Comment by l-arnold** [comment]
Well, it "sort of" restored over lapp.  
------------
TKLBAM Hostname association seemed to fall off after Restore.

Both Apache and Postgresql are not showing themselves in WEBMIN.  Can't run A2ENSITE from shell either.

I did just modify the openerp-server.conf file so I will see if I can open out of SSL.  Maybe (nope is the word service not running but postgresql seems to be)

Miss those Webmin clues.  Thinking I wont have the openerp/openuser (DB) setup but will restart
Reboot not seeming to work from Webmin....

After Reboot #2, still no Odoo.
I don't see openerp running as a service (within Webmin) either.

Oh well,  Gave it a wirl.
---
Ran turnkey-init
reset root and postgres  (no prompt for odoo admin password however)
changed confconsole to Odoo version after this and showed up in WebShell actually

interesting to get confconsole on a cloudserver actually. 

--------------
We really need to get this into the Library I think is the lesson here.

**Comment by l-arnold** [comment]
Placeholder: TESTED TKLBAM on a LAPP APPLIANCE.  
Didn't quite work (but old system restore and other subjects (like wrong restore target) so will abandon subject for now)
Good exercise anyway!

**Comment by JedMeister** [comment]
I would expect restore to PostgreSQL app to fail. LAPP should be close but you may still need to do some tweaks.

If you want to troubleshoot this I suggest that instead of doing a full backup, that you use the `--dump=/some/dir` switch to dump the backup to a directory (instead of uploading it). Then you can see exactly what is being backed up and tweak includes/excludes for future runs.

**Comment by l-arnold** [comment]
Almost on LAPP.  Everything restored including my "Webconsole".  However Odoo not running yet.

I also see in "firstboot inithooks" that there is a "97-tklbam-restore" file which may bump into our firstboot inithook (which is likewise not restoring - likely by design).

-----------
Manually ran the Yo Yo
root@lapp /# systemctl stop apache2.service
root@lapp /# systemctl stop openerp-server.service                                                                               
root@lapp /# systemctl stop postgresql.service                                                                                   
root@lapp /# systemctl start postgresql.service                                                                                  
root@lapp /# systemctl start openerp-server.service                                                                              
root@lapp /# systemctl start apache2.service 

No Errors Show, Still Not getting the OpenERP - Service (and system) to respond.
Opened up 4069 to Check (TKL/Amazon Firewall rules)

Even Dropped the Restored Database but still not starting.

Need to do this exercize with a newer system next but would prefer with the Odoo Install as writing over LAPP can cause Issues I expect still (though it shouldn't really)

----------
no efforts needed here for now.  Just a system forward check.

**Comment by l-arnold** [comment]
This should perhaps not be part of this thread.  However, though the service is "there" it does not seem to be starting.  Does not show as a running process in Webmin "running processes" or "bootup shutdown" Admin areas.

In currently active (need to pull forward) the process shows as noted earlier:
   533	openerp	19:03	python /opt/openerp/odoo/openerp-server --config=/opt/openerp/odoo/openerp-serve ...

This should have moved forward with TKLBAM.  It even reacts without error to various start commands but it does not start.

----------
Back to current issues now.  This was exploring how "transportable" this might be (ie could it be implemented on the cloud now).

**Comment by l-arnold** [comment]
Just saw your comment @JedMeister .  I think we are good for now.  Pretty much all came across (except a starting service)

**Comment by l-arnold** [comment]
I am going to delete "todays" thread of mine.  Not really part of this issue set.

**Comment by l-arnold** [comment]
I have set the "default" branch to DEV-WIP1 as I will otherwise put my "github edits" invariably into the wrong branch.  I need to work in WIP-DEV1 and then we can move to DEV etc.

We do have some changes in DEV which are stopping the OpenERP Service from Loading, so some focus needed there.

**Comment by JedMeister** [comment]
As an aside I think that including the git branch in the command prompt would avoid (or at least minimise) this. If you google you can find how to do this (IIRC it's called 'git-prompt'). I have been meaning to do it on my TKLDev server for a while but never got around to it. I actually think that adding it to TKLDev and making it default would be cool!

**Comment by l-arnold** [comment]
I have Deleted the "TKLDEV" build issues as I don't think these are subjects for the Odoo App per say.  Want to focus only on Odoo App subjects (can also have Ken's Branch Conversation here)

**Comment by l-arnold** [comment]
I learned today that "there can be problems" if Odoo is "abruptly stopped".  It would seem, therefore, worth putting a openerp-close command potentially into /etc/init.d/confconsole

Ideally this would use the ".init" which by my understanding is in the same folder:  /etc/init.d/openerp-server  (should we perhaps consider renaming to openerp.init again?  I actually think the old version of openerp.init was a softlink to openerp-server)

Also, I wonder if the "services" start stop that we use address this file or are they only addressing etc/odoo/openerp-server  ?

Enough questions.
Best.

**Comment by l-arnold** [comment]
Running dev-wip1 just went to Generate a Sales Order.  Was 

blockedReport (PDF)
Wkhtmltopdf failed (error code: -11). Message:

I was not aware of any changes, but perhaps there was a version change mentioned last week or so?  Did that hit the code?  Seems unlikely but I will look.

(update)  I do not see wkhtmltopdf having been loaded in the dev-wip1 branch at all.  Perhaps the new Odoo Code is expecting it to be there.

Prior we had had manually loaded whtmltox  in "10-dependencies"

The only real changes I am seeing in this realm on the current build is the removal of SAMBA.  There were a few root "calls" that were also removed, but would not expect them to effect wkhtml(etc).  Will look at what they are.  Perhaps there is a dependency that was removed that should not have been.

**Comment by l-arnold** [comment]
I've had 5 Permanent Pauses now trying to install wkhtmltopdf
Happening at different points.  Basically seems to be with the debian package servers.

I am getting the "Odoo-Init" to work in stopping with the following "down yo-yo" set of commands.

systemctl stop apache2.service
cd /etc/init.d
/bin/bash openerp-server stop  
systemctl stop postgresql.service   

Unfortunately the After a "Debian pause"  I am getting:

root@dev-wip1 ~# apt-get install wkhtmltopdf       

E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)  
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?

Trying a Restart now, but generally have been moving back to a "just prior" snapshot.  Not sure why the pauses in Debian Feeds.

**Comment by l-arnold** [comment]
Ok,  Finally got wkhtmltopdf to build.  However, Odoo is more "contrary" still.  This is the Error Response:

I will look at the last build to see if I can Print or email a formated Order.  (Beta 01)

Odoo Warning

Report (PDF)

Wkhtmltopdf failed (error code: -6). Message: The switch --header-spacing, is not support using unpatched qt, and will be ignored.The switch --header-html, is not support using unpatched qt, and will be ignored.The switch --footer-html, is not support using unpatched qt, and will be ignored.QXcbConnection: Could not connect to display

**Comment by DocCyblade** [comment]
Is this from a clean build of odoo? Or did you do a restore?

**Comment by l-arnold** [comment]
It is from a Clean Build of Odoo.  I did do a Database Backup from Beta 01.  Database Restore (complete database) to Beta 02.  Got the error in Beta 02 (my branch dev-wip1 - gen beta01 as was not able the other day to have branch dev open the service).

I did just reverse the Database process back to Beta 01 and was able to both Send Emails (formatted) and to Print, in fact with the same order that was not printing in Beta02.

I have been unable to find the meaning of error code -11 for wkhtmltopdf.  I did post on their GitPlace asking for feedback but nothing yet.

**Comment by l-arnold** [comment]
Only other thing I was working through in Beta 02 was getting magento connector to work.  Got that working.  Should have nothing to do with wkhtml(anything) however.  I will put the few changes made into Beta 01 and be sure I can still print.  Expecting I can, but perhaps there is some call that is routing some dependency path out of line there.  (BTW the Magento-CONNECTOR started flying.  Really great performance w/ the settings update)

**Comment by DocCyblade** [comment]
You making changes to build code or on the server its self post install? If you are making changes to build code what branch are you working on

**Comment by l-arnold** [comment]
(UPDATED for PHONE TYPOS)
Server itself post install.  

Ran VM snapshot
Installed wkhtmltopdf (which removed wkhtmltox)
Tested.  Got second error w column info above.
Went back to snapshot. So got wkhtmltox back.

The changes withe the connector were very minor in my running
etc/odoo/Openerp-server.conf
end
etc/init.d/openerp-server. Files.

Have not touched any repository files that I know of this week.  Have read some.

(update next Line ADDED)
Will do a "Fresh Install and move Data over to verify.  No Changes just the Database.

**Comment by l-arnold** [comment]
If making changes would do so to dev-wip1 Branch.  

I do want to update the "extras" folder a bit but need to get to that.  Was holding for a while.

If you have anything you want me to test on your side, let me know.
thanks,

**Comment by l-arnold** [comment]
OK.  Getting print/email etc off of FRESH BUILD Beta 02.

Likely something in the start cycles around the connector broke that.  Will have to debug.  They are not in the CONFIG FILES right now and can get a generated document (see attached) 

![generated order](https://cloud.githubusercontent.com/assets/5673448/10115472/f3410920-63c5-11e5-9378-5bca051119c4.jpg)

**Comment by l-arnold** [comment]
Not sure if my updates above telegraph through. Got it back on fresh beta 2 build.

**Comment by DocCyblade** [comment]
If you can type up a brief way to run through a test of Odoo. Maybe creating new demo database with demo data, and doing some adds edited, delete, and some other actions that would need testing, this way I can repeat the same tests. We could use this test matrix to test each release.

**Comment by l-arnold** [comment]
On wkhtmlrox error got this .  seemsbto have been a ram issue.  (will test again soon)
:https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2592#issuecomment-143402595

**Comment by l-arnold** [comment]
Driving about two hours.
Will send an outline when I arrive.of base tests.

**Comment by l-arnold** [comment]
Ken, this is my quick process.

(UPDATED)

Missing the Checkbox Format somehow .

-[ ] Build the App
-[ ] Install 
-[ ] See that Odoo is running (should land on the Database manager page - URL should be in confconsole I feel)
-[ ] Change Admin Password in Odoo Database Manager (testing control)
-[ ] install new database with new password
worth check that openerp-server.con admin-db variable also changes  -- sometimes Odoo can "cache" this but not change it if not writing to openerp-server.conf properly
-[ ] Install CRM Module
-[ ] Install Online Billing
-[ ] Install Sales Management
-[ ]  Create a Customer
-[ ]  Create a Quotation for the Customer
-[ ]  When quotation is saved, Choose Print  (or Email)
-[ ]  See that a Formatted Doc Shows up
-[ ]  Ideally see that an Email goes out (should default to Localhost and might work)
-[ ]  Check that Git is applying to opt/openerp/odoo files 
-[ ]  Check that various  addons added in 50-(additional addons) are showing in settings, module
-[ ]  ideally we should check those specific addons to see that they install.
-[ ]  base Odoo addons should install  (deliniate where those go vs outside addons - ie look at the code)
-[ ]  in Shell, test the /etc/init.d/openerp-server  (initialization) commands
     /bin/bash openerp-server stop
     /bin/bash openerp-server start
    /bin/bash openerp-server restart

```
*   (make sure system is actually running in browser.  if an issue will return "service unavailable"
*  best to try some of the -u  -d variables outlined earlier.
*  worth looking at the actua file to see how it is structured.  Not sure if that is an odoo creation of something of our legacy here to be honest.  (used to have a "softlink" called openero.init that would instagate that file and did not require the /bin/bash call.  That I found convenient.  Might be good to bring back somehow and leave it in /opt/openerp/  folder
```

-[ ]  

-[ ]  At this point lots of settings need to be made to be sure the system is working on a customized basis.

Other Tests to perform include migrating Data via "backup and restore" commands in the Odoo Database Manager.  I find this better than tklbam for the time being as tklbam is restoring virutually the full system (including the old git).

Worth moving some data files between machines.  Need to use "whole database option on the restore" command (not the "backup-restore" option)

wkhtmltox:
Need to run this dependency and not wkhtmltopdf debian package.

wkhtmltox (for emails, quotations, reports) is working in my base dev-wip1 branch (same as the jobrunner problem)

Unfortunately, my wkhtmltox is not working on the system that I configured "jobrunners" for in the Magento Connector.  I even reduced the number of workers to 1 (from 4).  running on 1 Gb of Ram.  Will briefly test 2 Gb but expecting it is not actually a Ram issue at this point.

incoming mail (in my docs).  Should not really be an issue in the install.  User needs to config their MX files etc.

ssl:  Also.  I can give you the template of how I install basic ssl with specific certs and not tkl certs

a2ensite odoo-12325  (web console post install).  I highly encourage this being kept in /etc/apached2/sites-available)
(it does not have to be loaded by default but would encourage it on every app personally)

OK,  all for now.

**Comment by l-arnold** [comment]
50-external-modules
come from
https://github.com/OCA

I have added descriptions of the repositories being pulled.

Have an unwieldy "Addons" line in openerp-server.conf

Would be good if we could break it into multiple lines.  Perhaps one for each addon.

Curretly reads like this  (perhaps we can use semicolons to break the line

addons_path = /opt/openerp/odoo/addons,/opt/openerp/oca/oca_server_tools,/opt/openerp/oca/connector,/opt/openerp/oca/connector-ecommerce,/opt/openerp/oca/connector-magento,/opt/openerp/oca/e-commerce,/opt/openerp/oca/product-attribute,/opt/openerp/oca/sale-workflow,/opt/openerp/oca/account-financial-tools,/opt/openerp/oca/connector-interfaces,/opt/openerp/oca/web,/opt/openerp/oca/website,/opt/openerp/oca/donation,/opt/openerp/oca/commission

**Comment by l-arnold** [comment]
Semicolons do not seem to work.  Applying Word Wrap will allow the line to be properly edited.  There may be another trick as well go having multiple entries in the addons path line above.

**Comment by JedMeister** [comment]
Hi guys,

I have been away the last few days and just had a really quick scan through the conversation. It seems to me that you guys are hard at it and getting closer and don't require anything specific from me at this point...!? Great work so far BTW! 

If there is anything you need from me (and I have missed it) please feel free to give me another ping! 

@l-arnold 

> Have an unwieldy "Addons" line in openerp-server.conf

All of your addons seem to be in `/opt/openerp/oca/`. From my very quick googling it seems to me that you should not need to actually include each path individually and that they should all get included automatically if you just reduced it to that base path (i.e. `/opt/openerp/oca/`). From what I have read many others seem to just have a single "add-ons" path which they then put all their addon subdirectories in and they all get picked up by Odoo (although it seems that you also need to enable them in the UI). There may be some subtlety that I have missed though....

**Comment by l-arnold** [comment]
RE whtmltox and jobrunner got the comment from Guewen pointing to "memory" configs.    Should test and document:  
https://github.com/OCA/connector-magento/issues/152#issuecomment-143685765

**Comment by l-arnold** [comment]
Worked through the wkhtmltox vs jobrunner memory issue.  Settings Documented Here
Updated on Checklist above:

(THIS SHOULD NOT BE OUR DEFAULT BUILD)!
https://github.com/OCA/connector-magento/issues/152

Moved the VM to 2 GB Ram (was running at 1gb and could run at 512mb)

Gave Odoo on openerp-server.conf

workers = 2 (was workers = 1)
limit_memory_hard = 1730150400

was 805306368

limit_memory_soft = 943718400 
was 671088640

**Comment by l-arnold** [comment]
SO,  How Do we bring these together?

The only variation we need are the Extra-Addons Branch

I will find my spreadsheets that outline the OCA Addons so we can perhaps make them Options.
Elstwise we can give instructions on how to integrate.

Wold be really cool if we became the Gateway for Odoo Addons.  Might get everyone to get their act together actually.

**Comment by l-arnold** [comment]
I realize there are instructions @DocCyblade   I just need to "absorb" a bit.
Thinking it will be "Copy Paste" to a large degree.

**Comment by l-arnold** [comment]
@JedMeister and @DocCyblade 
Jeremy had written "Have an unwieldy "Addons" line in openerp-server.conf
All of your addons seem to be in /opt/openerp/oca/. From my very quick googling it seems to me that you should not need to actually include each path individually and that they should all get included automatically if you just reduced it to that base path (i.e. /opt/openerp/oca/). From what I have read many others seem to just have a single "add-ons" path which they then put all their addon subdirectories in and they all get picked up by Odoo (although it seems that you also need to enable them in the UI). There may be some subtlety that I have missed though...."

---

So
I just tested this approach to addons and it wants to work but but it doesn't  fully work.  Icons for one for all the OCA (addl) Modules and Apps are not showing ujp.

Debugging some more.  I will put in all the "individual folders" and see if I get a different resu

It seems your approach though should work Jeremy.  Seems to work in the normal "Odoo/addons/ folder otherwise.

**Comment by l-arnold** [comment]
This is a Module after normal install.

![web id 315 view_type form model ir module module menu_id 53 action 37](https://cloud.githubusercontent.com/assets/5673448/10618665/77e1d81e-772e-11e5-9b2a-7a1af4cae2c8.jpg)

What I am getting with shorter Addons folder call  (see the incomplete Install)

![web](https://cloud.githubusercontent.com/assets/5673448/10618680/8d70a2d2-772e-11e5-98a9-f7dfaa00f31b.jpg)

How it shouild generally be looking:

![web](https://cloud.githubusercontent.com/assets/5673448/10618816/3513c6e0-772f-11e5-830c-7a899319d9f1.jpg)

These are the missing Icons (visible among others)

![web](https://cloud.githubusercontent.com/assets/5673448/10618871/9a096faa-772f-11e5-892f-9dc801829405.jpg)

**Comment by l-arnold** [comment]
Basically complete.  Closing this now.
Closed up on TKL-Odoo @DocCyblade
